name: Test
on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    # Required for AWS credentials action
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Amplify project
        uses: ./
        with:
          region: ${{ secrets.REGION }}
          app-id: ${{ secrets.APP_ID }}
          role-arn: ${{ secrets.ROLE_ARN }}
