name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amplify Flutter Pull
        uses: ./
        with:
          region: us-west-2
          app-id: ${{ secrets.APP_ID }}
          role-arn: ${{ secrets.ROLE_ARN }}
